# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/zynq_top/zynq_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_top || ORIG_REF_NAME==zynq_top} -quiet] -quiet

# IP: bd/zynq_top/ip/zynq_top_processing_system7_0_1/zynq_top_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_top_processing_system7_0_1 || ORIG_REF_NAME==zynq_top_processing_system7_0_1} -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/XRPIX/serial_riscv/deploy/Pynq-Z2/pynq/pynq.gen/sources_1/bd/zynq_top/zynq_top_ooc.xdc
