# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/binhkieudo/Workspace/XRPIX/serial_riscv/deploy/Pynq-Z2/pynq/pynq.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_1/zynq_top_processing_system7_0_1.xci
# IP: The module: 'zynq_top_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binhkieudo/Workspace/XRPIX/serial_riscv/deploy/Pynq-Z2/pynq/pynq.gen/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_1/zynq_top_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_top_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/binhkieudo/Workspace/XRPIX/serial_riscv/deploy/Pynq-Z2/pynq/pynq.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_1/zynq_top_processing_system7_0_1.xci
# IP: The module: 'zynq_top_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/binhkieudo/Workspace/XRPIX/serial_riscv/deploy/Pynq-Z2/pynq/pynq.gen/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_1/zynq_top_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_top_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
